# Install tool packages
- name: Install required tool packages
  apt: pkg={{ item }} state=latest
  with_items:
    - tophat
    # https://trello.com/c/9jm6tVqU/381-add-tabix-to-the-image
    - tabix
    # https://trello.com/c/7x9svF7x/382-bar-chart-tool-error
    - gnuplot

- name: "Preinstall common packages (makes jupyterhub install faster)"
  apt: name={{ item }}
  with_items:
    - npm
    - nodejs-legacy
    - python3-pip
    - libfreetype6-dev # for matplotlib

- name: "Preinstall common scientific packages (makes jupyterhub install faster)"
  pip: name={{ item }} executable=pip3 state=latest
  with_items:
    - matplotlib
    - scipy
    - pandas
    # https://trello.com/c/7x9svF7x/382-bar-chart-tool-error
    - gnuplot-py
    
- name: Download the liftOver binary
  get_url: url=http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/liftOver dest=/usr/bin/liftOver mode=0775
