- name: GVL Utils - Configure the GVL init script to run as an upstart job
  template: src=gvlinit.j2 dest=/etc/init/gvlinit.conf

- name: GVL Utils - Copy gvl scripts
  copy: src=scripts dest={{ gvl_install_path }} mode=0755 owner="ubuntu"

- name: GVL Utils - Clone gvl_commandline_utilities
  git: repo={{ gvl_cmdline_repository }} dest={{ gvl_cmdline_utils_path }} accept_hostkey=yes

- name: GVL Utils - Set ownership of git folder to ubuntu
  file:
    path: '{{ gvl_cmdline_utils_path }}'
    state: 'directory'
    owner: 'ubuntu'
    group: 'ubuntu'
    recurse: yes
