- include: install_system_packages.yml
  when: not only_cleanup

- include: install_gvldash.yml
  when: gvl_install_dash and not only_cleanup

- include: install_cmdline_utils.yml
  when: not only_cleanup

- include: configure_nginx.yml
  when: cm_configure_nginx and not only_cleanup

- include: configure_desktop.yml
  when: cm_install_novnc and not only_cleanup

- include: install_tool_packages.yml
  when: gvl_install_dash and not only_cleanup
